### ISSUE TITLE
TypeError: eye() takes at least 2 arguments (2 given)

### ISSUE THREAD

**Issue by Abraxas3d** [riccardoscalco/Pykov#17]
Traceback (most recent call last):
File "organelle.py", line 1325, in <module>
composer()
File "organelle.py", line 1044, in composer
phrase_lengths.append(P.kemeny_constant())
File "/usr/local/lib/python2.7/dist-packages/pykov.py", line 1270, in kemeny_constant
Z = self.fundamental_matrix()
File "/usr/local/lib/python2.7/dist-packages/pykov.py", line 1246, in fundamental_matrix
p = self.steady()._toarray(el2pos)
File "/usr/local/lib/python2.7/dist-packages/pykov.py", line 971, in steady
Q = ss.eye(m, format='csr') - P
TypeError: eye() takes at least 2 arguments (2 given)

What should I check first?

**Comment by Abraxas3d** [comment]
kemeny_constant() works on a macbook and on a desktop mac, but fails with above messages on a Raspberry Pi running Raspian. Same code on all devices. 

I'm using this for a demonstration in a pipe organ at Maker Faire this coming weekend (October 3-4). Because of the error, I'm going to skip the part that uses this (the algorithmic composition). It's a drag to leave it out, but I don't have time before the Faire to dig into it and find out why eye() gets two arguments - yet exits with an error. 

After the Faire, if I can figure out what's going on, I'll try and fix it for the Pi. 

So far, everything else in poky seems to be working on the Pi.
